### ISSUE TITLE
Missunderstanding of the obstacle avoidance example

### ISSUE THREAD

**Issue by pgarcia-dev** [fuzzylite/fuzzylite#118]
Hello,
This is not a report of a bug or an issue (I think) but I read on https://www.fuzzylite.com/forums/topic/https-fuzzylite-com-help/ you prefer us to ask our questions here. 

I am executing the obstacle avoidance example in C++ on the website, and I am getting this output:

➜  web git:(main) ✗ ./example-static-11
src/main.cpp (58):obstacle.input = 0.000 => steer.output = 0.667
src/main.cpp (58):obstacle.input = 0.020 => steer.output = 0.666
src/main.cpp (58):obstacle.input = 0.040 => steer.output = 0.666
src/main.cpp (58):obstacle.input = 0.060 => steer.output = 0.664
src/main.cpp (58):obstacle.input = 0.080 => steer.output = 0.662
src/main.cpp (58):obstacle.input = 0.100 => steer.output = 0.660
src/main.cpp (58):obstacle.input = 0.120 => steer.output = 0.657
src/main.cpp (58):obstacle.input = 0.140 => steer.output = 0.653
src/main.cpp (58):obstacle.input = 0.160 => steer.output = 0.649
src/main.cpp (58):obstacle.input = 0.180 => steer.output = 0.644
src/main.cpp (58):obstacle.input = 0.200 => steer.output = 0.638
src/main.cpp (58):obstacle.input = 0.220 => steer.output = 0.632
src/main.cpp (58):obstacle.input = 0.240 => steer.output = 0.625
src/main.cpp (58):obstacle.input = 0.260 => steer.output = 0.618
src/main.cpp (58):obstacle.input = 0.280 => steer.output = 0.610
src/main.cpp (58):obstacle.input = 0.300 => steer.output = 0.602
src/main.cpp (58):obstacle.input = 0.320 => steer.output = 0.593
src/main.cpp (58):obstacle.input = 0.340 => steer.output = 0.584
src/main.cpp (58):obstacle.input = 0.360 => steer.output = 0.575
src/main.cpp (58):obstacle.input = 0.380 => steer.output = 0.565
src/main.cpp (58):obstacle.input = 0.400 => steer.output = 0.554
src/main.cpp (58):obstacle.input = 0.420 => steer.output = 0.544
src/main.cpp (58):obstacle.input = 0.440 => steer.output = 0.533
src/main.cpp (58):obstacle.input = 0.460 => steer.output = 0.522
src/main.cpp (58):obstacle.input = 0.480 => steer.output = 0.511
src/main.cpp (58):obstacle.input = 0.500 => steer.output = 0.500
src/main.cpp (58):obstacle.input = 0.520 => steer.output = 0.489
src/main.cpp (58):obstacle.input = 0.540 => steer.output = 0.478
src/main.cpp (58):obstacle.input = 0.560 => steer.output = 0.467
src/main.cpp (58):obstacle.input = 0.580 => steer.output = 0.456
src/main.cpp (58):obstacle.input = 0.600 => steer.output = 0.446
src/main.cpp (58):obstacle.input = 0.620 => steer.output = 0.435
src/main.cpp (58):obstacle.input = 0.640 => steer.output = 0.425
src/main.cpp (58):obstacle.input = 0.660 => steer.output = 0.416
src/main.cpp (58):obstacle.input = 0.680 => steer.output = 0.407
src/main.cpp (58):obstacle.input = 0.700 => steer.output = 0.398
src/main.cpp (58):obstacle.input = 0.720 => steer.output = 0.390
src/main.cpp (58):obstacle.input = 0.740 => steer.output = 0.382
src/main.cpp (58):obstacle.input = 0.760 => steer.output = 0.375
src/main.cpp (58):obstacle.input = 0.780 => steer.output = 0.368
src/main.cpp (58):obstacle.input = 0.800 => steer.output = 0.362
src/main.cpp (58):obstacle.input = 0.820 => steer.output = 0.356
src/main.cpp (58):obstacle.input = 0.840 => steer.output = 0.351
src/main.cpp (58):obstacle.input = 0.860 => steer.output = 0.347
src/main.cpp (58):obstacle.input = 0.880 => steer.output = 0.343
src/main.cpp (58):obstacle.input = 0.900 => steer.output = 0.340
src/main.cpp (58):obstacle.input = 0.920 => steer.output = 0.338
src/main.cpp (58):obstacle.input = 0.940 => steer.output = 0.336
src/main.cpp (58):obstacle.input = 0.960 => steer.output = 0.334
src/main.cpp (58):obstacle.input = 0.980 => steer.output = 0.334
src/main.cpp (58):obstacle.input = 1.000 => steer.output = 0.333

I’m pretty sure I’m missing something because I have read a lot of documentation and as shown in the PDF on the examples I understand that given an input of 1 you should get 0 as an output. 

Could you please tell me if I am missing something and if so, give me any URL I can check? I would appreciate this a lot because as I already said I have read a lot of Documentation and I don’t get it. Thanks.

**Comment by pgarcia-dev** [comment]
Any suggestion here would we be appreciated. Thanks.

**Comment by jcrada** [comment]
Hi,

The example works as it is designed. The defuzzifier computes the centroid of the output value, so based on that it will not be the values that you want. See image attached. You can change the defuzzifier to LargestOfMaximum and get what you want.

The app QtFuzzyLite is key to understanding the operation of fuzzy logic controllers. Give it a try.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/303131/217350917-03a76cec-0302-40ca-89f4-16a96d0bb30f.png">

Cheers.
