### ISSUE TITLE
Outdated Doxygen URL in README.md

### ISSUE THREAD

**Issue by mich-j** [fuzzylite/fuzzylite#119]
Hello, 
I just noticed that Doxygen URL in README.md is out of date, it should be: `www.doxygen.nl` instead of `www.doxygen.org`.

**Comment by mich-j** [comment]
I have a quick fix for that, although I'm not certain where to commit it. See #120

**Comment by jcrada** [comment]
Thanks, `development` is the proper branch to contribute at the moment.
