### ISSUE TITLE
Outdated guideline hyperlink in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mich-j** [fuzzylite/fuzzylite#120]
Hello,
One of the hyperlinks in CONTRIBUTING.md points to _master_ branch: _Pull requests are made to the [master](https://github.com/fuzzylite/fuzzylite/tree/master) branch, not the release branch_, allthough there is no _master_ branch. Do you mean _main_ branch?

**Comment by jcrada** [comment]
Hi @mich-j . Thanks for your comments.
I need to sort out the git strategy when I come back to this full time. In the meantime, I think `development` is the most up-to-date branch to contribute to.

**Comment by mich-j** [comment]
@jcrada, I tried to commit but I get a Permission denied 403 error. I am on the `development` branch. Do you know maybe what could be the problem?

**Comment by jcrada** [comment]
Interesting. I'm not sure what's going on. Can you compare your development branch with the one in fuzzylite? Just wondering if I (embarrassingly) did a force push and left your branch in an invalid state?

**Comment by mich-j** [comment]
Yes, it's the same, I cloned the whole repo once again just to be sure. I checked out to `development` branch and then checked out to a new branch `fix/119`. When I do `git push --set-upstream origin fix/119` to push my branch and then make a pull request, I got this: 
```
ERROR: Permission to fuzzylite/fuzzylite.git denied to mich-j.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Maybe my workflow is wrong?

**Comment by jcrada** [comment]
Oh, yes, you need to fork fuzzylite, create a branch in your fork and submit the pull request from there. Does that make sense?

**Comment by jcrada** [comment]
All good. Many thanks for your contribution.

**Comment by mich-j** [comment]
Superb. Thank you too!
