### ISSUE TITLE
example error undefined reference to 'fl::Engine::Engine(std::string const&)' and relocation error

### ISSUE THREAD

**Issue by seungjaemoon** [fuzzylite/fuzzylite#151]
Hi
Now, I am trying to solve fuzzy logic in C++ using fuzzylite.
So I installed fuzzylite and tried to test the example, but errors occurred.

Ubuntu 14.04

At ObstacleAvoidance.cpp test, I got this error

undefined reference to 'fl::Engine::Engine(std::string const&)'
collect2: error: ld returned 1 exit status

At application test, I got another error

./example-dynamic-11: relocation error: /home/user/fuzzylite-6.0/release/bin/libfuzzylite.so.6.0: symbol _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

How can i fix them?

**Comment by jcrada** [comment]
How are you building your test and application?
Do you have a branch to reproduce the error?
Have you looked the documentation about compiling?
