### ISSUE TITLE
Create unit tests using Catch

### ISSUE THREAD

**Issue by jcrada** [fuzzylite/fuzzylite#36]
Unit tests are an important part of development to ensure the operation of the software does not break over time. While the results of the fuzzylite library are thoroughly and accurately tested in over 30 (Mamdani and Takagi-Sugeno) examples against the results obtained with the Matlab fuzzy logic toolbox,  the fuzzylite library lacks formal unit tests. An effort should be made to progressively create unit tests for each class in the library. 

My research suggests that Catch (github.com/philsquared/Catch) is the most appropriate framework to develop the unit tests given that (1) the tests are very easy to create, read, and incorporate, (2) Catch can be used as a header-only library, thereby only requiring the inclusion of a header file, and (3) Catch is free, open source, and has a GPL compatible open source license (Boost Software License - Version 1.0).

**Comment by jcrada** [comment]
No, there are no automatic tests in this version. Are you interested in collaborating by writing some tests?

**Comment by janisozaur** [comment]
I saw some being introduced in https://github.com/fuzzylite/fuzzylite/commit/03bf16264094f3934b1c392eb7b51450ecfeadb2 and I can still see `FL_BUILD_TESTS` being part of CMake, which I found confusing as to why the tests are gone.

I don't think I have any tests to contribute, but I have one patch, I'll submit it in a moment.

**Comment by jcrada** [comment]
The version in development has some tests, and what you see in `CMakeLists` is a merge from the development branch.

**Comment by janisozaur** [comment]
`release` seems to be using updated setup on travis involving docker, while `develop` looks to operate directly on bare system. Do you have plans to unify that?

**Comment by jcrada** [comment]
Yes, in the next month or so I expect to better organise this.

**Comment by DilHem** [comment]
Hey All,
Its Urgent,

Can anyone provide me C language code for fuzzy logic speed controller. I'm doing this Using ENERGIA interface.
I'm taking my inputs using a ultrasonic sensor and after fuzzy methods the outputs are taken by DC motors as their inputs and then after they are going to control the speed or the rotation speed of DC motor.

I'm thankful if anyone can provide the C language code for this.

Thank You

Energia code for fuzzy speed controller on C language

**Comment by jcrada** [comment]
A bit too late, but working through this at the moment.
