### ISSUE TITLE
could the -Wunused-variable warnings be solved?

### ISSUE THREAD

**Issue by josch** [fuzzylite/fuzzylite#43]
Hi,

with gcc-5 one gets multiple warnings of the following sort:

```
/tmp/fuzzylite/fuzzylite/./fl/fuzzylite.h:119:18: warning: ‘fl::inf’ defined but not used [-Wunused-variable]
     const scalar inf = std::numeric_limits<scalar>::infinity();
                  ^
```

Since they are emitted by nearly every single compilation unit, they needlessly clutter the build log. Could something be done to remove the warning? For example by adding an `__attribute__(unused)`?

**Comment by jcrada** [comment]
I think I will temporarily add the `-Wunused-variable` parameter to the compilation flags. I am not sure if `__attribute__(unused)` is cross platform. Would this be of satisfaction?

**Comment by josch** [comment]
Maybe it's not the best idea to add `-Wunused-variable` because that would hide actual problems with other unused variables. The reason why in Debian we compile with maximum verbosity is to automatically detect any problems with the source so it's important not to hide them.

As for compiler compatibility, how about doing it the following way:

```c++
#ifdef __GNUC__
const scalar inf __attribute__ ((unused)) = std::numeric_limits<scalar>::infinity();
#else
const scalar inf = std::numeric_limits<scalar>::infinity();
#endif
