### ISSUE TITLE
question about member ship function 

### ISSUE THREAD

**Issue by minotaur-0** [fuzzylite/fuzzylite#51]
Hi 
First, I want to thank you for great job : ) 
I want to ask this member ship function is implemented on your software ? how it is called ?
![zoz](https://cloud.githubusercontent.com/assets/13518553/9283967/ce92ad3e-42cf-11e5-8d3f-fc3d050ea9c2.png)

**Comment by jcrada** [comment]
I think that function is the PiShape. Please, checkout QtFuzzyLite and you will find out. 
For future questions not related to the development of fuzzylite, please use the forums at www.fuzzylite.com/forums/.

**Comment by minotaur-0** [comment]
thank you :+1:
