### ISSUE TITLE
Travis should use cached docker images

### ISSUE THREAD

**Issue by janisozaur** [fuzzylite/fuzzylite#72]
I saw your builds on Travis take great amount of time. I'd like to suggest a way of improving their performance.

On each job of a build you build a docker image, which doesn't vary a lot – all but the compiler are the same. I'd like to suggest you use docker hub to have automated builds and only download the image instead of building it each time.

Depending on how messy you're willing to get, you can set it up so that you can have base system (all *but* the compiler) built and only install compiler on travis, or you can create a directory per each of the compilers and have docker hub build all of them for you (this would involve specifying compiler as tag of the image).

Hub will build an image for you whenever there is a new commit in the repo, so worst case scenario you would be one commit behind on the image freshness, this can be worked around (say by using another repo; pushing a dummy commit to trigger rebuild on hub or manually triggering build).

Right now it takes 6 minutes to build the image, while the whole job takes 11 minutes: https://travis-ci.org/fuzzylite/fuzzylite/jobs/194574656#L106. For comparison, pulling a pre-built image with all required packages takes only 30s: https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/202723200#L266.

It would be really kind of you to conserve the (finite and limited) resources Travis offers.

See https://hub.docker.com/.

**Comment by jcrada** [comment]
Thank you for your suggestion. 
The development (master) branch has been changed to use a cached image.
Cheers.
