### ISSUE TITLE
fuzzylite stores build path in output binary

### ISSUE THREAD

**Issue by josch** [fuzzylite/fuzzylite#87]
This is not only a potential privacy violation but also makes fuzzylite unreproducible.

Read more about why reproducible builds matter here: https://reproducible-builds.org/

If I read the code correctly, then the culprit is `FL_BUILD_PATH` together with `FL__FILE__`.

**Comment by jcrada** [comment]
Thanks @josch . This is something I want to fix, but I am not sure what the best solution might be. Do you have any suggestions?

**Comment by josch** [comment]
In `fuzzylite/fl/fuzzylite.h` you write:

    #define FL__FILE__ std::string(__FILE__).substr(std::string(FL_BUILD_PATH).size())

With:

    add_definitions(-DFL_BUILD_PATH="${CMAKE_SOURCE_DIR}")

This will remove the source directory from what the user sees when any path is being printed but it will still embed the source directory into the resulting binaries so that the `substr()` methods can be executed on the original contents of `__FILE__` at runtime. So even though the user doesn't see it, the unreproducible data still exists. I see two ways to work around this:

 1. strip off `CMAKE_SOURCE_DIR` using cmake functions instead of doing it at runtime
 2. since gcc 8 and clang 10 you can use `add_compile_options(-fmacro-prefix-map=${CMAKE_SOURCE_DIR}=.)` which will replace all instances of `${CMAKE_SOURCE_DIR}` in `__FILE__` by `.` (or any other static prefix of your choosing).

**Comment by jcrada** [comment]
Do you have some examples of option (1)?

**Comment by josch** [comment]
You might be able to use `cmake_path(RELATIVE_PATH <path-var> [BASE_DIRECTORY <input>] [OUTPUT_VARIABLE <out-var>])` from https://cmake.org/cmake/help/latest/command/cmake_path.html#generation similar to how it is done here:

https://stackoverflow.com/a/54377777/784669

**Comment by josch** [comment]
Alternatively, since all sources are in the `fuzzylite` directory, you could also use cmake to find the right-most instance of `/fuzzylite/` in the source file path and strip away anything before that.

**Comment by jcrada** [comment]
Got rid of `BUILD_PATH`, a bit late, but better late than never.
