### ISSUE TITLE
Releasing this under vcpkg

### ISSUE THREAD

**Issue by ieshaan12** [fuzzylite/fuzzylite#91]
Is there an open source installation file for fuzzylite in C++, similar to pyfuzzylite in Python?
Instead of copying all the source code?

**Comment by jcrada** [comment]
Yes, we use Cmake in FuzzyLite. Please refer to the readme file in GitHub.

**Comment by jcrada** [comment]
Oh, you mean like a package manager. In more than a few Linux installations you can do `apt-get install fuzzylite`.

**Comment by jcrada** [comment]
I just checked, you should be able to use `vcpkg`. FuzzyLite is listed in https://vcpkg.io/en/packages.html
